config/routes.rb
Clairvoyance::Application.routes.draw do
  resource :session, only: [:new, :create, :destroy]

  resources :users do
    resources :boards, only: :index
    resources :cards, only: :index
  end

  resources :boards, except: :index do
    resources :catagories, only: [:new, :create]
    resources :memberships, only: [:new, :create]
    # route does not need to be nested. fix at next controlled state
    put 'catagories/reorder', to: 'catagories#reorder'
    put 'cards/reorder', to: 'cards#reorder'
  end
  
  resources :catagories, only: [:update, :destroy] do
    resources :cards, only: [:new, :create]
  end


  resources :cards, only: [:show, :update, :destroy] do
    resources :participations, only: [:new, :create]
    resources :checklists, only: [:new, :create]
  end

  resources :checklists, only: [] do
    resources :checklist_items, only: [:new, :create]
  end

  resources :checklist_items, only: [:update, :destroy]

  resources :participations, only: :destroy

  resources :memberships, only: [:edit, :show, :update, :destroy]

  root to: "boards#index"
end

app/models/catagory.rb
class Catagory < ActiveRecord::Base
  attr_accessible :board_id, :title, :sort_idx

  belongs_to :board,
  class_name: "Board",
  foreign_key: :board_id,
  primary_key: :id

  has_many :cards,
  dependent: :destroy,
  class_name: "Card",
  foreign_key: :catagory_id,
  primary_key: :id

  validates :board_id, :title, :sort_idx, presence: true
  validates :title, uniqueness: { scope: :board_id }
  
  def self.generate_reorder(list_set, current_user_id)
    function_key = (current_user_id.to_s) + "_" + (SecureRandom::hex 8)
    
    list_idx = {}
    list_set.values.each do |list_params|
      list_idx[list_params[:id].to_i] = list_params[:sort_idx].to_i
    end
    
    variables = []
    case_statement = []
    
    list_idx.keys.each_with_index do |id, idx|
      if ( idx < list_idx.keys.count - 1 || list_idx.keys.count == 1)
        case_statement << "when id = #{id} then #{list_idx[id]}"
      else
        case_statement << "else #{list_idx[id]}"
      end
      variables << "var#{idx}"
    end
    
    <<-SQL
      CREATE FUNCTION reorder_#{function_key}( #{ variables.map { |var| var + " integer"}.join(', ') } )
      RETURNS void AS
      $$
      UPDATE catagories
      SET sort_idx = (case #{case_statement.join(' ')} end)
      WHERE id IN (#{ variables.join(', ') });
      $$ 
      LANGUAGE SQL;
      
      SELECT reorder_#{function_key}(#{list_idx.keys.map { |id| id.to_s }.join(', ') });
      
      DROP FUNCTION reorder_#{function_key}(#{variables.map { |var| "integer" }.join(', ') });
    SQL
  end
end

app/controllers/catagories_controller.rb
class CatagoriesController < ApplicationController
  before_filter :logged_in_clearance
  # needs member clearance

  def new
    @board = Board.find(params[:board_id])
    @catagory = Catagory.new
    render :new
  end

  def create
    @board = Board.find_by_id(params[:board_id])
    @catagory = Catagory.new(
      title: params[:catagory][:title],
      sort_idx: params[:catagory][:sort_idx],
      board_id: params[:board_id]
    )
    p @catagory
    if @catagory.save
      if request.xhr?
        render json: @catagory
      else
        redirect_to board_url(params[:board_id])
      end
    else
      p @catagory.errors.full_messages
      if request.xhr?
        render json: @catagory
      else
        flash[:errors] = @catagory.errors.full_messages
        render :new
      end
    end
  end
  
  def update
    @catagory = Catagory.find(params[:id])
    if @catagory.update_attributes(params[:catagory])
      if request.xhr?
        render json: @catagory
      else
        redirect_to board_url(params[:board_id])
      end
    else
      if request.xhr?
        head status: 422
      else
        redirect_to root_url
      end
    end
  end

  def destroy
    if request.xhr?
      @catagory = Catagory.find(params[:id])
      @catagory.destroy
      
      head status: 200
    else      
      @catagory = Catagory.find(params[:id])
      @board = @catagory.board
      @catagory.destroy

      redirect_to board_url(@board)
    end
  end
  
  def reorder
    if request.xhr?      
      ActiveRecord::Base.connection.execute(Catagory.generate_reorder(params[:catagories], current_user.id))
      head status: 200
    else
      redirect_to root_url
    end
  end
end

app/helpers/catagories_helper.rb
module CatagoriesHelper
end

app/views/catagories/_delete_menu.html.erb
<div class="option-menu hidden-form hidden"
data-id="<%= id %>">
	<div class="exit">
    <%= image_tag("exit.png")%>
	</div>

	<h1>List Actions</h1>
	<ul>
		<li>
			<ul>
				<li>
					<%= button_to "Delete List", catagory_url(id), form_class: "delete-list", method: :delete, remote: true %>
				</li>
			</ul>
		</li>
	</ul>
</div>

app/views/catagories/_new.html.erb
<form id="add-list-form" 
class="hidden"
action="<%= board_catagories_url(board) %>" 
method="POST" 
accept-charset="utf-8"
data-remote="true">

	<input type="hidden"
	name="authenticity_token"
	value="<%= form_authenticity_token %>">
	
	<input type="hidden"
	id="catagory-sort-idx"
	name="catagory[sort_idx]"
	value="<%= idx %>">

	<input type="text"
	name="catagory[title]">
	<br>

	<button class="save">Add</button>
</form>

app/views/catagories/_option_menu.html.erb
<div class="option-menu hidden-form hidden"
data-id="<%= id %>">
	<div class="exit">
    <%= image_tag("exit.png")%>
	</div>

	<h1>List Actions</h1>
	<ul>
		<li>
			<ul>
				<li>
					<%= button_to "Delete List", catagory_url(id), form_class: "delete-list", method: :delete, remote: true %>
				</li>
			</ul>
		</li>
	</ul>
</div>

app/views/catagories/_title_form.html.erb
<form
class="rename-list hidden"
action="<%= catagory_url(catagory) %>" 
method="POST" 
accept-charset="utf-8"
data-remote="true">
  <input type="hidden" name="_method" value="PUT">

	<input type="hidden"
	name="authenticity_token"
	value="<%= form_authenticity_token %>">

		<textarea name="catagory[title]"><%= catagory.title %></textarea>
	<br>

	<p>
		<input class="save" type="submit" value="Rename"> 
	</p>
</form>

app/views/catagories/new.html.erb
<%= render partial: "catagories/new", locals: { board: @board } %>