config/routes.rb
Clairvoyance::Application.routes.draw do
  resource :session, only: [:new, :create, :destroy]

  resources :users do
    resources :boards, only: :index
    resources :cards, only: :index
  end

  resources :boards, except: :index do
    resources :catagories, only: [:new, :create]
    resources :memberships, only: [:new, :create]
    # route does not need to be nested. fix at next controlled state
    put 'catagories/reorder', to: 'catagories#reorder'
    put 'cards/reorder', to: 'cards#reorder'
  end
  
  resources :catagories, only: [:update, :destroy] do
    resources :cards, only: [:new, :create]
  end


  resources :cards, only: [:show, :update, :destroy] do
    resources :participations, only: [:new, :create]
    resources :checklists, only: [:new, :create]
  end

  resources :checklists, only: [] do
    resources :checklist_items, only: [:new, :create]
  end

  resources :checklist_items, only: [:update, :destroy]

  resources :participations, only: :destroy

  resources :memberships, only: [:edit, :show, :update, :destroy]

  root to: "boards#index"
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  include BCrypt

  attr_accessible :token, :bio, :email, :password_digest, :full_name,
    :initials, :username, :password, :password_verify, :avatar
     
  has_attached_file :avatar, styles: {
    big: '170x170#',
    thumb: '34x34#' 
  }
     
  attr_accessor :password, :password_verify

  has_many :created_boards,
  inverse_of: :creator,
  class_name: "Board",
  foreign_key: :creator_id,
  primary_key: :id

  has_many :memberships,
  class_name: "Membership",
  foreign_key: :user_id,
  primary_key: :id

  has_many :member_boards, through: :memberships, source: :board

  has_many :participations,
  class_name: "Participation",
  foreign_key: :user_id,
  primary_key: :id

  has_many :cards, through: :participations, source: :card

  validates :email, presence: true
  validate :email_formatted
  validates :password, :password_verify, presence: true, on: :create
  validates :password, length: { minimum: 6, maximum: 20 }, on: :create
  validate :match_passwords, on: :create

  after_validation :set_password, on: :create
  after_validation :set_token, on: :create

  def self.generate_token
    SecureRandom::urlsafe_base64 16
  end

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    return user && user.has_password?(password) ? user : nil
  end
  
  def self.is_valid_password? (password)
    password.length >= 6 && password.length <= 20
  end

  def set_token
    self.token = User.generate_token
  end
  
  def has_password? (password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def change_password (new_password)
    self.password_digest = BCrypt::Password.create(new_password)
    self.save
  end

  private
  def match_passwords
    errors.add(:password, "must match") unless @password == @password_verify
  end
  
  def email_formatted
    errors.add(:email, "invalid email") unless self.email =~ /^[A-Za-z0-9.\-]*\@[A-Za-z0-9.]*\.[A-Za-z]*$/
  end

  def set_password
    self.password_digest = BCrypt::Password.create(@password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :personal_clearance, only: [:edit, :update, :destroy]
  before_filter :logged_in_clearance, only: [:home, :edit]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      login!(@user)

      UserMailer.welcome_email(@user).deliver!

      redirect_to root_url
    else
      render :new
    end
  end

  def show
    if @user = User.includes(:member_boards, :cards).find_by_id(params[:id])
      render :show
      
    else
      flash[:errors] = "User not found"
      redirect_to new_user_url
    end
  end
  
  def edit
    @user = User.find_by_id(params[:id])
    render :edit
  end

  def update  
    @current_user.update_attributes(strong_user_params)
    
    update_password if params[:user].include?(:password)
    update_email if params[:user].include?(:email)
    
    if request.xhr?
      render json: @current_user
    else
      redirect_to edit_user_url(@current_user)
    end
  end

  def destroy
  end

  def home
    render :home
  end
  
  private
  def strong_user_params
    params[:user].select do |k,v|
      ["username", "avatar", "full_name", "initials", "bio"].include?(k)
    end
  end
  
  def update_password    
    if @current_user.has_password? (params[:user][:password])

      if params[:user][:new_password] == params[:user][:new_password_again]

        if User.is_valid_password? (params[:user][:new_password])
         
          puts "changing pw"
          @current_user.change_password (params[:user][:new_password])
          
        else
          flash[:errors] = "Password must be 6-20 characters"
        end
        
      else
        flash[:errors] = "Passwords do not match."
      end

    else
      flash[:errors] = "Invalid password."
    end
  end
  
  def update_email
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_avatar.html.erb
<div class="avatar">
	<% if user.avatar.exists? %>
    <%= image_tag user.avatar.url(:thumb) %>
	<% else %>
		<%= image_tag ("default_avatar.jpg") %>
	<% end %>
</div>

app/views/users/_boards_menu.html.erb
<nav class="board-list hidden">
	<button class="exit">X</button>
  <h4>Boards</h4>
  <ul>
		<li>
			<h5>My Boards</h5>
			<ul>
	      <% current_user.member_boards.each do |board| %>
	      <a href="<%= board_url(board) %>">
	        <li><%= board.title %></li>
	      </a>
	      <% end %>
			</ul>
		</li>
		<li>
			<ul>
				<a href="<%= root_url %>">
					<li>
						See All Boards
					</li>
				</a>
				<a class="new-board-link" href="<%= new_board_url %>">
					<li> 
						New Board...
					</li>
				</a>
				<%= render partial: "boards/new", locals: { id: 0, hidden: true } %>
			</ul>
		</li>
  </ul>
</nav>

app/views/users/_header.html.erb
<header class="user-header group">
	<a href="/">
	  <div class="logo">
	    <%= image_tag("strello.png")%>
	  </div>
	</a>

  <nav class="header-nav">
    <ul>
      <li>
        <div class="boards-button group">
          <div>
						<%= image_tag ("boards.png") %>
          </div>
          <span>
						Boards
					</span>
        </div>
      </li>
      <li>
        <div class="avatar">
					<% if current_user.avatar.exists? %>
			      <%= image_tag current_user.avatar.url(:thumb) %>
					<% else %>
						<%= image_tag ("default_avatar.jpg") %>
					<% end %>
        </div>
      </li>
    </ul>
  </nav>

	<%= render partial: "users/boards_menu" %>
	
	<%= render partial: "users/logout_menu" %>
</header>

app/views/users/_logout_menu.html.erb
<nav class="logout-menu hidden-form hidden">
	<div class="exit">
    <%= image_tag("exit.png")%>
	</div>
	
	<h1><%= current_user.email %></h1>
	<ul>
		<li>
			<ul>
				<a href="<%= user_boards_url(current_user) %>">
					<li>
						Boards
					</li>
				</a>
				<a href="<%= user_cards_url(current_user) %>">
					<li>
						Cards
					</li>
				</a>
				<a href="<%= edit_user_url(current_user) %>">
					<li>
						Account Settings
					</li>
				</a>
			</ul>
		</li>
		<li>
			<ul>
				<a class="new-board-link" href="<%= new_board_url %>">
					<li>
						New Board...
					</li>
				</a>
				<%= render partial: "boards/new", locals: { id: -1, hidden: true } %>
			</ul>
		</li>
		<li>
			<ul>
				<li>
					<%= button_to "Log Out",session_url, method: :delete, class: 'logout' %>
				</li>
			</ul>
		</li>
	</ul>
	
</nav>

app/views/users/_profile_nav.html.erb
<section class="user-nav">
	<div class="big-avatar <%= "clickable" if user == current_user %>">
		<% if user.avatar.exists? %>
      <%= image_tag user.avatar.url(:big) %>
		<% else %>
			<%= image_tag ("default_avatar.jpg") %>
		<% end %>
		<% if user == current_user %>
		<div class="change-avatar hidden">
			<span>Change Avatar</span>
		</div>
		<% end %>
	</div>
		<% if user == current_user %>
			<%= render partial: "users/edit_forms/avatar" %>
		<% end %>
	<ul>
		<li id="user-info">
			<span id="user-email"><%= user.full_name %></span>
			<span id="user-username">@<%= user.username %></span>
		</li>
		<li class="user-links">
			<ul>
				<a href="<%= user_boards_url(user) %>">
					<li>
						Boards
					</li>
				</a>
				<a href="<%= user_cards_url(user) %>">
					<li>
						Cards
					</li>
				</a>
			</ul>
		</li>
		<% if user == current_user %>
		<li class="user-links">
			<ul>
				<li class="new-board-link">
					New Board...
				</li>
				<%= render partial: "boards/new", locals: { id: 2, hidden: true } %>
			</ul>
		</li>
		<li class="user-links">
			<ul>
				<a href="<%= edit_user_url(user) %>">
					<li>
						Account Settings
					</li>
				</a>
			</ul>
		</li>
		<% end %>
	</ul>
</section>

app/views/users/edit.html.erb
<%= render partial: "users/header" %>

<article class="user-pages group">
	<section id="account-settings">
		<ul>
			<h2>Account Details</h2>
			<li data-type="meta">
				Change Name, Initials, or Bio
			</li>
			<%= render partial: "users/edit_forms/meta" %>
			
			<li data-type="email">
				Change Email Address
			</li>
			<%= render partial: "users/edit_forms/email" %>
			
			<li data-type="avatar">
				Change Avatar
			</li>
			<%= render partial: "users/edit_forms/avatar" %>
			
			<li data-type="password">
				Change Password
			</li>
			<%= render partial: "users/edit_forms/password" %>
		</ul>			
	</section>
	
	<%= render partial: "users/profile_nav", locals: { user: current_user } %>
</article>

app/views/users/home.html.erb
<%= render partial: "users/header" %>

app/views/users/home_backbone.html.erb
<script type="application/json" id="bootstrapped_user">
  { "user": <%= current_user.to_json(
    include: [:cards, :member_boards]
    ).html_safe %> }
</script>

<script>
  $(document).ready(function () {
    CV.usersInitialize({
      header: $('header'),
      finished: $('#finished'),
      current: $('#current'),
      pending: $('#pending'),
      footer: $('footers')
    });
  });
</script>

app/views/users/new.html.erb
<article class="user-background">
	<div class="login-logo">
	  <%= image_tag("login.png")%>
	</div>

	<section class="new-user-view users group">
		<div class="login-left">
			<h1>Create An Account</h1>

			<!-- <% if @user.errors.any? %>
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
			<% end %> -->

			<form action="<%= users_url %>" method="POST" accept-charset="utf-8">
				<input type="hidden"
				name="authenticity_token"
				value="<%= form_authenticity_token %>">

				<label>Email
					<br>
					<input class="field"
					type="text"
					name="user[email]"
					value="<%= @user.email %>"
					placeholder="e.g., ender@battle.edu">
				</label>
				<br>

				<label>Password
					<br>
					<input class="field"
					type="password"
					name="user[password]"
					placeholder="e.g., ••••••••••••••••">
				</label>
				<br>

				<label>Password (again)
					<br>
					<input class="field"
					type="password"
					name="user[password_verify]"
					placeholder="e.g., ••••••••••••••••">
				</label>
				<br>
			
				<input class="save" type="submit" value="Sign Up">
				<br>
				Already have an account? <%= link_to "Log In.", new_session_url %>
			</form>
		</div>

		<div class="login-right">
			<%= render partial: "sessions/guest_login" %>
		</div>
	</section>
</article>

app/views/users/show.html.erb
<%= render partial: "users/header" %>

<article class="user-pages group">
	<section class="board-index">

		<h2><%= @user.email %></h2>
		

	</section>

	<%= render partial: "users/profile_nav", locals: { user: @user } %>

</article>