config/routes.rb
Clairvoyance::Application.routes.draw do
  resource :session, only: [:new, :create, :destroy]

  resources :users do
    resources :boards, only: :index
    resources :cards, only: :index
  end

  resources :boards, except: :index do
    resources :catagories, only: [:new, :create]
    resources :memberships, only: [:new, :create]
    # route does not need to be nested. fix at next controlled state
    put 'catagories/reorder', to: 'catagories#reorder'
    put 'cards/reorder', to: 'cards#reorder'
  end
  
  resources :catagories, only: [:update, :destroy] do
    resources :cards, only: [:new, :create]
  end


  resources :cards, only: [:show, :update, :destroy] do
    resources :participations, only: [:new, :create]
    resources :checklists, only: [:new, :create]
  end

  resources :checklists, only: [] do
    resources :checklist_items, only: [:new, :create]
  end

  resources :checklist_items, only: [:update, :destroy]

  resources :participations, only: :destroy

  resources :memberships, only: [:edit, :show, :update, :destroy]

  root to: "boards#index"
end

app/models/board.rb
class Board < ActiveRecord::Base
  attr_accessible :title, :creator_id

  belongs_to :creator,
  inverse_of: :created_boards,
  class_name: "User",
  foreign_key: :creator_id,
  primary_key: :id

  has_many :memberships,
  class_name: "Membership",
  foreign_key: :board_id,
  primary_key: :id

  has_many :members, through: :memberships, source: :user

  has_many :catagories,
  class_name: "Catagory",
  foreign_key: :board_id,
  primary_key: :id

  has_many :cards, through: :catagories, source: :cards

  validates :title, :creator_id, presence: true
  validates :title, uniqueness: { scope: :creator_id }
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_filter :logged_in_clearance, only: [:index, :new, :create]
  before_filter :member_clearance, only: [:show, :update]

  def index
    if !!params[:user_id]
      @user = User.find(params[:user_id])
    else
      @user = current_user
    end
    
    @boards = Board.includes(:members).select { |board| board.members.include?(@user) }
    render :index
  end

  def new
    @board = Board.new
    render :new
  end

  def create
    @board = current_user.created_boards.build(params[:board])
    if @board.save
      Membership.create(user_id: current_user.id, board_id: @board.id, admin: true)
      Catagory.create(board_id: @board.id, title: "To Do", sort_idx: 0)
      Catagory.create(board_id: @board.id, title: "Doing", sort_idx: 1)
      Catagory.create(board_id: @board.id, title: "Done", sort_idx: 2)
      redirect_to board_url(@board)
    else
      redirect_to root_url
    end
  end

  def show
    @board = Board.includes(:members, catagories: :cards).find(params[:id])
    render :show
  end
  
  def update
    @board = Board.find(params[:id])
    @board.update_attributes(params[:board])
    if request.xhr?
      render json: @board
    else
      redirect_to board_url(@board)
    end
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_board.html.erb
<article 
class="board" 
data-id="<%= board.id %>" 
style="min-width: <%= (board.catagories.count + 1) * 290 %>px;">

  <ul id="board-lists" class="group">
    <% board.catagories.sort { |x, y| x.sort_idx <=> y.sort_idx }.each do |catagory| %>
    <li class="list" data-id="<%= catagory.id %>" data-idx="<%= catagory.sort_idx %>">

      <h4>
				<%= catagory.title %>
				<div class="option-icon">
					<%= image_tag("option-icon.png")%>
				</div>
			</h4>
			<%= render partial: "catagories/option_menu", locals: { id: catagory.id } %>
			<%= render partial: "catagories/title_form", locals: { catagory: catagory } %>

      <ul class="group">
        <% catagory.cards.sort { |x, y| x.sort_idx <=> y.sort_idx }.each do |card| %>
          <%= render partial: "cards/card", locals: { card: card, catagory: catagory } %>
        <% end %>
      </ul>
			
      <div class="new-card-form">
        <div class="new-card hidden">
          <%= render partial: "cards/new", locals: { catagory: catagory, idx: catagory.cards.count } %>
        </div>
        <div class="add-card">Add a card...</div>
      </div>

    </li>
    <% end %>
   
    <li id="new-catagory-li">
			<%= render partial: "catagories/new", locals: { board: board, idx: board.catagories.count } %>
     
			<div class="new-list">
				 Add a List...
			</div>
    </li>
    
  </ul>
</article>

app/views/boards/_header.html.erb
<header class="board-header group">
  <div id="board-name">
    <h2><span><%= board.title %></span></h2>
  </div>
	<%= render partial: "boards/title_form", locals: { board: board } %>
	<%= render partial: "boards/sidebar", locals: { board: board } %>
</header>

app/views/boards/_new.html.erb
<form class="new-board-form hidden-form<%= ' hidden' if hidden %>"
data-id="<%= id %>"
action="<%= boards_url %>" 
method="POST" 
accept-charset="utf-8">
	<div class="exit">
    <%= image_tag("exit.png")%>
	</div>

	<h1>Create Board</h1>
	
	<input type="hidden"
	name="authenticity_token"
	value="<%= form_authenticity_token %>">

	<label>Title
		<br>
		<input type="text"
		name="board[title]"
		placeholder="Untitled Board">
	</label>

	<p><input class="save" type="submit" value="Create"></p>
</form>

app/views/boards/_sidebar.html.erb
<div id="board-sidebar-link">
	<h5>&#9668; <span>Show sidebar</span></h5>
</div>
<div id="board-sidebar" class="hidden">
	<div id="board-sidebar-exit">
		&#9658;
	</div>
	<h3>Members</h3>
	<ul id="member-list" class="group">
	<% board.members.each do |member| %>
		<li>
			<%= render partial: "users/avatar", locals: { user: member } %>
		</li>
	<% end %>
	</ul>
	<button id="new-membership-button" class="menu-button group">
		<div class="member-icon-white">
			<%= image_tag ("people_head.png") %>
		</div>
		<div class="member-icon-blue">
			<%= image_tag ("people_head_blue.png") %>
		</div>
		<span>
			Add Members...
		</span>
	</button>
	<%= render partial: "memberships/new", locals: { board: board } %>
</div>

app/views/boards/_title_form.html.erb
<form id="rename-board"
class="hidden-form hidden"
action="<%= board_url(board) %>" 
method="POST" 
accept-charset="utf-8"
data-remote="true">
	<div class="exit">
	  <%= image_tag("exit.png")%>
	</div>
	
	<h1>Rename Board</h1>

  <input type="hidden" name="_method" value="PUT">

	<input type="hidden"
	name="authenticity_token"
	value="<%= form_authenticity_token %>">

	<label>
		<input type="text"
		name="board[title]"
		value="<%= board.title %>">
	</label>
	<br>

	<p><input class="save" type="submit" value="Rename"></p>
</form>

app/views/boards/index.html.erb
<%= render partial: "users/header" %>

<article class="user-pages group">
	<section class="board-index">
		<div id="my-boards-icon">
	    <%= image_tag("people_head.png")%>
		</div>
		<h1>My Boards</h1>
		<% if @user == current_user %>
		<a class="new-board-link" href="<%= new_board_url %>">
			<div id="new-board-icon">
				<%= image_tag("boards_dark.png")%>
			</div>
			
			<span>New board...</span>
		</a>
		<%= render partial: "boards/new", locals: { id: 1, hidden: true } %>
		<% end %>
		<ul>
			<% @boards.each do |board| %>
			<li>
				<a href="<%= board_url(board) %>">
					<nav>
						<%= board.title %>
					</nav>
				</a>
			</li>
			<% end %>
		</ul>
	</section>

	<%= render partial: "users/profile_nav", locals: { user: @user } %>

</article>

app/views/boards/new.html.erb
<%= render partial: "boards/new", locals: { id: 0, hidden: false } %>

app/views/boards/show.html.erb
<section id="all-headers">
	<%= render partial: "users/header", locals: { board: @board } %>
	<%= render partial: "header", locals: { board: @board } %>
</section>

<%= render partial: "boards/board", locals: { board: @board } %>

<%= render partial: "cards/view" %>