config/routes.rb
Clairvoyance::Application.routes.draw do
  resource :session, only: [:new, :create, :destroy]

  resources :users do
    resources :boards, only: :index
    resources :cards, only: :index
  end

  resources :boards, except: :index do
    resources :catagories, only: [:new, :create]
    resources :memberships, only: [:new, :create]
    # route does not need to be nested. fix at next controlled state
    put 'catagories/reorder', to: 'catagories#reorder'
    put 'cards/reorder', to: 'cards#reorder'
  end
  
  resources :catagories, only: [:update, :destroy] do
    resources :cards, only: [:new, :create]
  end


  resources :cards, only: [:show, :update, :destroy] do
    resources :participations, only: [:new, :create]
    resources :checklists, only: [:new, :create]
  end

  resources :checklists, only: [] do
    resources :checklist_items, only: [:new, :create]
  end

  resources :checklist_items, only: [:update, :destroy]

  resources :participations, only: :destroy

  resources :memberships, only: [:edit, :show, :update, :destroy]

  root to: "boards#index"
end

app/models/card.rb
class Card < ActiveRecord::Base
  attr_accessible :description, :due_date, :start_date, :title, :catagory_id, :sort_idx

  belongs_to :catagory,
  class_name: "Catagory",
  foreign_key: :catagory_id,
  primary_key: :id

  has_one :board, through: :catagory, source: :board

  has_many :members, through: :board, source: :members

  has_many :checklists,
  class_name: "Checklist",
  foreign_key: :card_id,
  primary_key: :id
  
  has_many :checklist_items, through: :checklists, source: :checklist_items

  has_many :participations,
  inverse_of: :card,
  class_name: "Participation",
  foreign_key: :card_id,
  primary_key: :id

  has_many :participants, through: :participations, source: :user

  validates :title, :catagory_id, presence: true
  
  def self.generate_reorder(card_set, user_id)
    function_key = (user_id.to_s) + "_" + (SecureRandom::hex 8)
  
    card_idx = {}
    card_set.values.each do |card_params|
      card_idx[card_params[:id].to_i] = {
        catagory_id: card_params[:catagory_id].to_i,
        sort_idx: card_params[:sort_idx].to_i
      }
    end
    
    variables = []
    case_state_idx = []
    case_state_catagory = []
    
    card_idx.keys.each_with_index do |id, idx|
      if (idx < card_idx.keys.count - 1 || card_idx.keys.count == 1)
        case_state_idx << "when id = #{id} then #{card_idx[id][:sort_idx]}"
        case_state_catagory << "when id = #{id} then #{card_idx[id][:catagory_id]}"        
      else
        case_state_idx << "else #{card_idx[id][:sort_idx]}"
        case_state_catagory << "else #{card_idx[id][:catagory_id]}"
      end
      variables << "var#{idx}"
    end
    
    <<-SQL
      CREATE FUNCTION reorder_#{function_key}( #{ variables.map { |var| var + " integer"}.join(', ') } )
      RETURNS void AS
      $$
      UPDATE cards
      SET sort_idx = (case #{case_state_idx.join(' ')} end), catagory_id = (case #{case_state_catagory.join(' ')} end)
      WHERE id IN ( #{ variables.join(', ') } );
      $$ 
      LANGUAGE SQL;
      
      SELECT reorder_#{function_key}(#{card_idx.keys.map { |id| id.to_s }.join(', ') });
      
      DROP FUNCTION reorder_#{function_key}(#{variables.map { |var| "integer" }.join(', ') });
    SQL
  end
  
  def can_edit?(user)
    
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_filter :logged_in_clearance

  def index
    if !!params[:user_id]
      @user = User.find(params[:user_id])
    else
      @user = current_user
    end
    
    @cards = Card.includes(:participants).select { |card| card.participants.include?(@user) }
    
    render :index
  end

  def new
    if @catagory = Catagory.includes(:board).find(params[:catagory_id])
      @card = Card.new
      @card.catagory = @catagory
      render :new
    else
      flash[:errors] = "Board not fonud"
      redirect_to user_url(current_user)
    end
  end

  def create
    @catagory = Catagory.includes(:board).find(params[:catagory_id])

    @card = Card.new(params[:card])
    @card.catagory_id = @catagory.id

    if @card.save
      if request.xhr?
        render json: @card
      else
        redirect_to board_url(@catagory.board)
      end
    else
      flash[:errors] = @card.errors.full_messages
      render :new
    end
  end

  def show
    @card = Card.find(params[:id])
    
    if request.xhr?
      render json: {
        card: @card.as_json( include: [
          :checklists,
          :checklist_items,
          :catagory,
          :participations,
          :board
        ]),
        members: @card.members.map { |member| {member: member, avatar_url: member.avatar.url(:thumb)} },
        participants: @card.participants.map { |participant| {participant: participant, avatar_url: participant.avatar.url(:thumb)} }
      }
    else
      redirect_to root_url
    end
  end

  def update
    @card = Card.includes({checklists: [:checklist_items]}, :participants, catagory: :board).find(params[:id])

    if @card.update_attributes(params[:card])
      if request.xhr?
        render json: @card
      else
        redirect_to board_url(@card.catagory.board)
      end
    else
      render :edit
    end
  end

  def destroy
    @card = Card.find(params[:id])
    @board = @card.board
    @card.destroy
    
    if request.xhr?
     head status: 200
    else      
      redirect_to board_url(@board)
    end
  end
  
  def reorder
    if request.xhr?
      ActiveRecord::Base.connection.execute(Card.generate_reorder(params[:cards], current_user.id))
      head status: 200
    else
      redirect_to root_url
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
<li class="mini-card"
data-id="<%= card.id %>" 
data-idx="<%= card.sort_idx %>"
<% if !!catagory %>
data-catagory-id="<%= catagory.id %>"
<% end %>
>

	<a class="card-link" href="/cards/<%= card.id %>">
	  <div class="card-text card">
			<div class="option-icon">
				<%= image_tag("option-icon.png")%>
			</div>
	    <%= card.title %>
	  </div>
	</a>
	<%= render partial: "cards/option_menu", locals: { id: card.id } %>
</li>

app/views/cards/_description_form.html.erb
<form id="card-description-form"
action="<%= card_url(@card) %>"
method="POST"
accept-charset="utf-8"
data-remote="true">
  <input type="hidden" name="_method" value="PUT">

	<input type="hidden"
	name="authenticity_token"
	value="<%= form_authenticity_token %>">


  <div class="card-description">
    <div class="card-description-detail detail">
      <h4><%= @card.description %></h4>
      <br>
      <button class="card-edit-button">Edit the card description.</button>
    </div>
    <div class="card-description-input input hidden">
      <textarea name="card[description]"
      class="card-description-textarea"><%= @card.description %></textarea>
      <button id="card-description-button" class="save">Save</button>
    </div>
  </div>
</form>

app/views/cards/_new.html.erb
<form class="actually-card-new-form"
action="<%= catagory_cards_url(catagory) %>"
method="POST"
accept-charset="utf-8"
data-remote="true">

	<input type="hidden"
	name="authenticity_token"
	value="<%= form_authenticity_token %>">
	
	<input type="hidden"
	class="card-sort-idx"
	name="card[sort_idx]"
	value="<%= idx %>">

	<textarea name="card[title]"></textarea>
  <br>

  <button class="save">Add</button>
</form>

app/views/cards/_option_menu.html.erb
<div class="option-menu hidden-form hidden"
data-id="<%= id %>">
	<div class="exit">
    <%= image_tag("exit.png")%>
	</div>

	<h1>Card Actions</h1>
	<ul>
		<li>
			<ul>
				<li>
					<%= button_to "Delete Card", card_url(id), form_class: "delete-card", method: :delete, remote: true %>
				</li>
			</ul>
		</li>
	</ul>
</div>

app/views/cards/_title_form.html.erb
<form id="card-title-form"
action="<%= card_url(@card) %>"
method="POST"
accept-charset="utf-8"
data-remote="true">
  <input type="hidden" name="_method" value="PUT">

	<input type="hidden"
	name="authenticity_token"
	value="<%= form_authenticity_token %>">


  <div class="card-title">
    <span class="card-title-detail detail">
      <h3><%= @card.title %></h3> in list <strong><%= @card.catagory.title %></strong>
    </span>
    <div class="card-title-input input hidden">
    	<textarea name="card[title]"
      class="card-title-textarea"><%= @card.title %></textarea>
      <button id="card-title-button" class="save">Save</button>
    </div>
  </div>
  <br>
</form>

app/views/cards/_view.html.erb
<article id="card-view" class="hidden">
	<div class="card-page group">
		<div class="exit">
	    <%= image_tag("card-exit.png")%>
		</div>
		<div class="loading">
			<%= image_tag("loading.gif")%>
		</div>
		<section class="card-main">		
		</section>
		<section class="sidebar">
		</section>
	</div>
</article>

app/views/cards/edit.html.erb
<div class="card-page group">	
	<button class="exit" data-board-id="<%= @card.board.id %>">X</button>
	
  <section class="card-main">
    <%= render "title_form" %>
    <%= render "description_form" %>

    <div class="checklists">
      <ul>
      <% @card.checklists.sort { |x, y| x.created_at <=> y.created_at }.each do |checklist| %>
        <li>
          <h3><%= checklist.title %></h3>
          <ul>
            <% checklist.checklist_items.each do |item| %>
            <li><%= item.title %></li>
            <% end %>
          </ul>
          <%= link_to "Add item", new_checklist_checklist_item_url(checklist) %>
        </li>
      <% end %>
      </ul>
    </div>
  </section>

  <section class="sidebar">
    <ul>
      <li>
        <h4>Members</h4>
        <ul class="members">
          <% @card.participants.each do |member| %>
          <li data-id="<%= member.id %>">
            <div class="avatar">
              <%= image_tag("happy-cat1.jpg")%>
            </div>
          </li>
          <% end %>
        </ul>
        <!-- new_card_participation_url(@card) -->
        <button class="assign-member-button sidebar">Assign...</button>
				<div class="assign-member hidden">
					<h4>Members</h4>
					<%= render partial: "participations/new", locals: { card: @card } %>
				</div>
      </li>

      <li>
        <h4>Actions</h4>
        <ul>
          <li>
            <!-- new_card_checklist_url(@card) -->
            <button class="add-checklist-button sidebar">Add checklist...</button>
          </li>
        </ul>
      </li>
    </ul>
  </section>
</div>

app/views/cards/index.html.erb
<%= render partial: "users/header" %>

<article class="user-pages group">
	<section class="card-index">
		<ul class="group">
			<% @cards.each do |card| %>
				<%= render partial: "cards/card", locals: { card: card, catagory: nil } %>
			<% end %>
		</ul>
	</section>

	<%= render partial: "users/profile_nav", locals: { user: @user } %>

</article>

<%= render partial: "cards/view" %>

app/views/cards/new.html.erb
<%= render partial: "cards/new", locals: { card: @card } %>

app/views/cards/show.html.erb
<div class="card-page group">
	<a href="<%= board_url(@card.board) %>">
		<button class="exit">X</button>
	</a>
	
  <section class="card-main">
    <%= render "title_form" %>
    <%= render "description_form" %>

    <div class="checklists">
      <ul>
      <% @card.checklists.sort { |x, y| x.created_at <=> y.created_at }.each do |checklist| %>
        <li>
          <h3><%= checklist.title %></h3>
          <ul>
            <% checklist.checklist_items.each do |item| %>
            <li><%= item.title %></li>
            <% end %>
          </ul>
          <%= link_to "Add item", new_checklist_checklist_item_url(checklist) %>
        </li>
      <% end %>
      </ul>
    </div>
  </section>

  <section class="sidebar">
    <ul>
      <li>
        <h4>Members</h4>
        <ul class="members">
          <% @card.participants.each do |member| %>
          <li data-id="<%= member.id %>">
            <%= render partia	l: "users/avatar", locals: { user: member } %>
          </li>
          <% end %>
        </ul>
        <button class="assign-member-button sidebar">Assign...</button>
      </li>
      <li>
        <h4>Actions</h4>
        <ul>
          <li>
            <button class="add-checklist-button sidebar">Add checklist...</button>
          </li>
        </ul>
      </li>
    </ul>
  </section>
</div>